Add vm jobs to ubuntu-advantange-client
canonical/server-jenkins-jobs pull request #144
Opened 2020-10-14 20:06 UTC by lucasmoura

Running the full set of uaclient test in travis CI is taking a lot of time (around 2h30), we want to move some of these tests to a daily jenkins job.

We are starting by moving the vm tests, which are currently not been run on travis due to time concerns as well. We will move other test in the near future.

PS: We cannot merge this branch until this [PR](https://github.com/canonical/ubuntu-advantage-client/pull/1204) lands in uaclient, since it sets some necessary definitions for vm tests to run

2020-10-15 14:53 UTC, paride requested changes
Thanks for this! There are some things to adjust, but nothing critical. We may also want to add two wrappers to the jobs: `workspace-cleanup` and `timeout`. I'd also go for a shallow git clone unless the full git history is needed for some reason (e.g. past git tags).

I'll be happy to do the changes, I setup similar jobs several times now so I have all the relevant bits handy. OTOH if you want to get to know our Jenkins and JJB things better I'll also be happy to do some review back and forth.

2020-10-15 14:53 UTC, paride commented on ubuntu-advantage-client/jobs.yaml
> +          set -ex
Duplicate `-x`.

2020-10-15 14:53 UTC, paride commented on ubuntu-advantage-client/jobs.yaml
> +          cd /tmp/uac
I'd prefer the job to run in the Jenkins WORKSPACE instead of changing dir to `/tmp`, so everything is contained there. As is this will also hit "directory already existing" issues when re-running the job, as `/tmp/uac` is not cleaned up.

2020-10-15 14:53 UTC, paride commented on ubuntu-advantage-client/parameters.yaml
> +          description: git url to clone project from
It is sometimes useful to be able to specify a branch to clone, so the tests can be easily run against a PR branch. I have these "template" parameters for doing this: https://github.com/canonical/server-jenkins-jobs/blob/master/lma/parameters.yaml

2020-10-15 14:53 UTC, paride commented on ubuntu-advantage-client/jobs.yaml
> +          TOXENV=behave-16-04
Looking at https://github.com/canonical/ubuntu-advantage-client/pull/1204 is seems that the tox environments are called `behave-vm-16.04` (and similar). The TOXENV should probably be updated here.

2020-10-15 14:53 UTC, paride commented on ubuntu-advantage-client/default.yaml
> +      - uaclient-vm-18.04
We should really use a job template here, something like:
```
ubunturelease:
  - 16.04
  - 18.04
  - 20.04
jobs:
  - uaclient-vm-{ubunturelease}
```

2020-10-15 14:56 UTC, paride commented
The jobs call `./tools/run_lxd_integration_tests.sh`, but the script doesn't exist in the uac repository and isn't part of https://github.com/canonical/ubuntu-advantage-client/pull/1204/. Do you plan to add it in a separate PR?

Can we replace it with a direct `tox` call?

2020-10-15 15:18 UTC, paride commented
Added [WIP] in title mostly to signal this is blocked by https://github.com/canonical/ubuntu-advantage-client/pull/1204

2020-10-15 18:07 UTC, lucasmoura commented
@paride Thanks for the review. I have updated the code with the points you have raises. However, I am just unsure about the `ubunturelease` part. By just adding that into the yaml, the jobs will loop on them to construct the list of jobs to run ?

Also, thanks for spotting the typos on the tools script. Right now it is not a tox command because it need to perform additional steps before running the behave tests.

2020-10-16 08:55 UTC, paride commented
> However, I am just unsure about the `ubunturelease` part. By just adding that into the yaml, the jobs will loop on them to construct the list of jobs to run ?

Yes exactly. We need something like this in the project definition:
```
- project:
    name: ubuntu-advantage-client
    ubunturelease:
      - 16.04
      - 18.04
      - 20.04
    jobs:
      - uaclient-vm-{ubunturelease}
      - ubuntu-advantage-client-integration-ec2-terminate
```

The the `job` definition has to be changed to a `job-template` like:

```
- job-template:
    name: uaclient-vm-{ubunturelease}
    parameters:
      - uaclient
    wrappers:
      - workspace-cleanup
      - timeout:
          timeout: 50
          fail: true
    builders:
      - shell: |
          #!/bin/bash
          set -ex
          export TOXENV=behave-vm-{ubunturelease}

          git clone --depth 1 -b "$UABRANCH" "$UAREPO" ua-client
          cd ua-client
          ./tools/run_lxd_travis_integration_tests.sh
```
Note that I used `{ubunturelease}` in the builder definition. The TOXENV variable will be set to `behave-vm-16.04` (and similar), which I think matches the actual environment names in https://github.com/canonical/ubuntu-advantage-client/pull/1204/.

2020-10-16 09:06 UTC, paride requested changes

2020-10-16 09:06 UTC, paride commented on ubuntu-advantage-client/jobs.yaml
> +          ./tools/run_lxd_travis_integration_tests.sh
Let's also add a publisher here:
```
    publishers:
      - email-server-crew
```
so we'll get emailsl when the job build fails. (We actually don't because the `server-crew-qa` mailing list is broken, but we will once it's fixed.)

2020-10-16 09:06 UTC, paride commented on ubuntu-advantage-client/jobs.yaml
> +          set -e
Nit: let's have all the flags in one place (`set -ex`) instead of setting `-x` in the shebang and `-e` with `set`.

Or did you do it on purpose to also log the `set -e` bit?

2020-10-16 12:52 UTC, lucasmoura commented on ubuntu-advantage-client/jobs.yaml
> +          set -e
No, there is no problem changing that at all

2020-10-16 12:53 UTC, lucasmoura commented
Thanks for the review @paride. I have updated the code

2020-10-16 15:40 UTC, paride commented
@lucasmoura I didn't test it, but this now LGTM, thanks! For some reason Travis is taking a long time to run.

Once https://github.com/canonical/ubuntu-advantage-client/pull/1204 lands I'll test and land this, let's keep it in WIP state for the moment, if you agree.

2020-10-19 17:48 UTC, lucasmoura commented
@paride The vm tests PR landed on uaclient. I think we can merge this one now

2020-10-20 10:56 UTC, paride commented
I deployed the jobs without merging to test them, but they're failing like this:

```
+ TOXENV=behave-vm-18.04
+ git clone --depth 1 -b master https://github.com/canonical/ubuntu-advantage-client.git ua-client
Cloning into 'ua-client'...
+ cd ua-client
+ ./tools/run_lxd_travis_integration_tests.sh
cp: cannot stat '*-debs/*': No such file or directory
```

If I don't go wrong that's because the job doesn't perform the .deb package building, so there are no `deb-artifacts` to archive, so the script will require some tweaking.

Anyway I had a better look at the `run_lxd_travis_integration_tests.sh` wrapper, and apparently what it's doing is mainly setting up lxd from snap and cleaning up the source tree, e.g. by moving the .debs away (the failing step above).

In general I prefer the Jenkins job not do perform `sudo` operation or to reconfigure services like `lxd` which are shared with other jobs. Remember the the jobs do not run in an ephemeral environment.

The assumption that the Jenkins nodes have snap LXD configured is safe, and indeed just running
```
tox -e behave-vm-{ubunturelease}
```
in the job's script seems to work, I did it manually here: https://jenkins.ubuntu.com/server/job/uaclient-vm-16.04/2/.

It seems to me that we could safely skip the wrapper scripts and just have tox run. What do you think?

2020-10-20 12:36 UTC, lucasmoura commented
@paride Thanks for that context. Yes, I agree that we can move the script to call tox directly. I will update the code

2020-10-20 12:57 UTC, lucasmoura commented
@paride I have updated the code

2020-10-20 13:00 UTC, paride commented
@lucasmoura thanks! Just another thing: the job definition doesn't setup a trigger, which means that the jobs will only run if started manually. I think we want to automatically run the jobs daily. In this case you should add a `timed` trigger to the `job-template`:
```
    triggers:
      - timed: '@daily'
```

2020-10-20 13:38 UTC, paride approved these changes

2020-10-20 13:39 UTC, merged