oci unit: add postgresql
canonical/server-jenkins-jobs pull request #148
Opened 2020-11-05 18:19 UTC by paride

2020-11-05 18:21 UTC, paride commented
Note: I did some renaming, we'll need to delete the existing `lma-integration` job if you agree on the changes. Rationale in the commit message.

The postgresql job is defined with a project + job-template, so it will be very easy to add more jobs.

2020-11-05 18:44 UTC, sergiodj requested changes
Everything looks good!  The only comment I have is related to the `-lma` suffix, which is not needed anymore since we will be using this to test all OCI images, not only the LMA ones.

2020-11-05 18:44 UTC, sergiodj commented on oci/integration.yaml
> +    name: oci-integration-lma
You can drop the `-lma` suffix here, since this will cover more than the LMA packages.

2020-11-05 18:45 UTC, sergiodj commented
> Note: I did some renaming, we'll need to delete the existing `lma-integration` job if you agree on the changes. Rationale in the commit message.

Yeah, that is totally fine.

2020-11-06 11:28 UTC, paride commented on oci/integration.yaml
> +    name: oci-integration-lma
@sergiodj wouldn't it be better to have different jobs for different stacks? I was thinking of `oci-integration-lma` for LMA, `oci-integration-otherstack` for otherstack, and so on.

2020-11-06 15:47 UTC, paride commented on oci/integration.yaml
> +    name: oci-integration-lma
Marking resolved per MM discussion.

2020-11-06 15:47 UTC, merged