[WIP] Add remaining uaclient jobs
canonical/server-jenkins-jobs pull request #160
Opened 2020-12-08 20:10 UTC by lucasmoura

2020-12-08 22:07 UTC, blackboxsw commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +              credential-id: ua-azure-tenant-id
This is named ua-azure-tenant otherwise we get failures like https://jenkins.ubuntu.com/server/view/ua/job/uaclient-cleanup-stale-azure-vms/1/console

2020-12-08 22:50 UTC, blackboxsw commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +              credential-id: ua-aws-access-key
s/ua-aws-access-key/ua-aws-access-key-id/

2020-12-09 04:42 UTC, blackboxsw commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +    name: uaclient-vm-{ubuntuvmrelease}
While it's nice to have a simple job template that can be used for all uaclient-vm-{ubuntuvmrelease} release items, can we somehow ensure a time splay (distrubution) or a trigger sequence for these to make sure we aren't using KVM backend at the same time as other uaclient-vm jobs, cloud-init vm-based jobs and curtin vm-based jobs. Having too many kvm jobs running tends to kill our jenkins server.

2020-12-09 04:44 UTC, blackboxsw commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +    name: uaclient-azure-generic-{ubunturelease}
like the vm-based tests, I think we need to run azure-based tests sequentially and not in parallel especially because we will have to worry about hitting resource caps etc which had affected us in travis runs.

2020-12-09 12:15 UTC, paride requested changes

2020-12-09 12:15 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +    name: uaclient-vm-{ubuntuvmrelease}
This is true, OTOH it's really nice to have a single job template. The better way to fix the concurrency problem is to use this plugin:

https://plugins.jenkins.io/throttle-concurrents/

which allows to define job classes and throttle the number of concurrent builds per class. For example we could define a `ua-kvm-job` class and restrict it to 1 job/node, or even better define a more general `heavy-vm-job`, to be used across projects (ua/curtin/...). This way we could limit heave VM jobs to (say) 4 concurrent jobs per node, and that's it, no need to "chain" jobs like in curtin. I'd like to make this change in curtin too.

Unfortunately we don't have the plugin in our Jenkins. There's a RT open for it (@mitechie knows already), but IS didn't get to it yet. I can try to push a bit more for it, but it's difficult to get an ETA.

The other possibility I see is to use a matrix job, and have `{ubunturelease}` as an axis. I think the list can still be defined at the project level. Let's speak at standup, I can put together a prototype job and see if it works for us. Otherwise we'll have to "chain" the jobs.

2020-12-09 12:15 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/default.yaml
> +      - uaclient-unittest
While they do no harm, there's no need to have these jobs here, as they're not templated and don't use variables defined by the project. It's probably a bit safer not to have them here so they don't inherit variables we don't use.

2020-12-09 12:15 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/default.yaml
>        - ubuntu-advantage-client-integration-ec2-terminate
same for this one

2020-12-09 12:15 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +    node: torkoal
No need to limit these jobs to torkoal I think.

2020-12-09 12:15 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +    name: uaclient-azure-generic-{ubunturelease}
+1, see my other comment

2020-12-09 17:35 UTC, blackboxsw commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +    name: uaclient-vm-{ubuntuvmrelease}
Good suggestions @paride, as we mentioned in standup, let's go for matrix job at the moment to avoid too many concurrent vm-based jobs. And we can improve this when the plugin situation is sorted.

2020-12-12 00:38 UTC, blackboxsw approved these changes
LGTM changed azure-pro and  azure-generic to matrix and offset their timed job runs.

2020-12-12 00:39 UTC, merged