Add uaclient gcp test job to Jenkins
canonical/server-jenkins-jobs pull request #167
Opened 2021-01-12 14:08 UTC by lucasmoura

Add two jobs related to gcp in Jenkins. We are now introducing behave tests for generic gcp instances
and also a cleanup script to teardown instances that may not be deleted on the behave tests

2021-01-13 11:58 UTC, paride requested changes

2021-01-13 11:58 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +          python server-test-scripts/ubuntu-advantage-client/gcp_cleanup.py --credentials-path $GCP_CREDENTIALS_PATH --project ubuntu-rickh --region us-west2 --zone a
python -> python3

2021-01-13 11:58 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +      - timed: 'H 0,4 * * *'
Are we going to have other jobs starting GCP instances other than `uaclient-gcp-generic`? If that's the only job that will create instances to cleanup, then we can trigger this job when `uaclient-gcp-generic` ends  (with any state). The same as:

https://github.com/canonical/server-jenkins-jobs/blob/master/jenkins-jobs/cloud-init/integration-ec2.yaml#L27

2021-01-13 11:58 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +    node: torkoal
Let's not restrict this to torkoad (just drop this line). It should work on any node.

2021-01-13 11:58 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +          python3 -m venv /tmp/gcp-cleanup
I think it's better if jobs keep their files in the Jenkins workspace when possible, so here I'd drop the `/tmp` and work in the PWD Jenkins puts us in (the job workspace).

2021-01-13 11:58 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +          git clone https://github.com/canonical/pycloudlib.git
I think these are safe to `git clone --depth 1`.

2021-01-13 11:58 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +      - timed: 'H 3 * * *'
If we go with the job trigger approach this timed trigger can be made `H H * * *` for more randomness.

2021-01-13 12:00 UTC, paride commented
Let's wait for the squid change allowing `*.googleapis.com` to land before merging this. We'll likely need to set `https_proxy`.

2021-01-13 12:56 UTC, lucasmoura commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +      - timed: 'H 0,4 * * *'
Just to be sure, that job will be triggered even if the `ua-gce-generic` job fails, right ?

2021-01-13 12:59 UTC, lucasmoura commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +          python server-test-scripts/ubuntu-advantage-client/gcp_cleanup.py --credentials-path $GCP_CREDENTIALS_PATH --project ubuntu-rickh --region us-west2 --zone a
I did not specify that here because the command is running inside a python3 virtualenv

2021-01-13 13:05 UTC, lucasmoura commented
@paride code updated

2021-01-13 13:29 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +      - timed: 'H 0,4 * * *'
Yes, that's the `threshold: failure` thing

2021-01-13 13:32 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +          python server-test-scripts/ubuntu-advantage-client/gcp_cleanup.py --credentials-path $GCP_CREDENTIALS_PATH --project ubuntu-rickh --region us-west2 --zone a
Right!

2021-01-13 13:41 UTC, paride requested changes
Added one comment, for the rest LGTM.

2021-01-13 13:41 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +    publishers:
We also need to add an `email-server-crew-qa` publisher here, like https://github.com/canonical/server-jenkins-jobs/blob/master/jenkins-jobs/cloud-init/integration-ec2.yaml#L25.

We need this because this `publishers:` stanza replaces the publishers defined in `defaults.yaml` (where we already have `email-server-crew-qa`), and there's no way to tell JJB to append instead of replacing. I tried to find a workaround using yaml anchors, but it didn't really simplify things.

(The `email-server-crew-qa` sends emails to the broken mailing list, let's assume it will get fixed one day...)

2021-01-13 13:44 UTC, lucasmoura commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +    publishers:
Done

2021-01-14 13:05 UTC, paride requested changes

2021-01-14 13:05 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +          python server-test-scripts/ubuntu-advantage-client/gcp_cleanup.py --credentials-path $GCP_CREDENTIALS_PATH --project ubuntu-rickh --region us-west2 --zone a
I added `https_proxy=http://squid.internal:3128` from the Jenkins interface and it worked :) Let's add it here, re-deploy the jobs to Jenkins from your branch, test them, and then I think this can land.

2021-01-14 15:47 UTC, paride commented on jenkins-jobs/ubuntu-advantage-client/jobs.yaml
> +          https_proxy=http://squid.internal:3128 UACLIENT_BEHAVE_GCP_PROJECT=ubuntu-rickh tox -e behave-gcpgeneric-$UBUNTURELEASE
`launchpad.net` can't be accessed via proxy, I'm not sure why. Just add a `no_proxy=launchpad.net` here.

2021-01-15 15:17 UTC, paride approved these changes
All the jobs are green, let's merge this.

2021-01-15 15:17 UTC, merged