oci: email server-crew-qa@l.c.c and OCI devels directly
canonical/server-jenkins-jobs pull request #168
Opened 2021-01-29 15:48 UTC by paride

2021-01-29 17:19 UTC, sergiodj requested changes

2021-01-29 17:19 UTC, sergiodj commented on jenkins-jobs/oci/integration.yaml
> +          recipients: server-crew-qa@lists.canonical.com sergio.durigan@canonical.com
I think it's worth copying @lucaskanashiro here as well.

2021-01-29 17:19 UTC, sergiodj commented on jenkins-jobs/oci/unit.yaml
> +          recipients: server-crew-qa@lists.canonical.com sergio.durigan@canonical.com
Likewise.

2021-02-05 15:56 UTC, paride commented
Added @lucaskanashiro

2021-02-05 16:00 UTC, sergiodj commented
Thanks, @paride.  @bryceharrington is also getting involved in the OCI work, but he's still learning the ropes so we can add him later.  I'm approving this PR.

2021-02-05 16:00 UTC, merged